version: 1.0.{build}
configuration: 
  - Debug
  - Release
  - EI_Debug
  - EI_Release
  - EI_Debug_Net40
  - EI_Release_Net40


#AppVeyor only use this file if you use GitHub repo.
#If you use Git public repo, you must copy this lines to your build settings

# scripts to run before build
before_build:
    - nuget restore      #install missing nuget packages
    - '"%ProgramFiles(x86)%\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe" build\TweakAntlr.fsscript packages\Antlr4.4.5.3\build\Antlr4.targets'    #fsharp script fixing Antlr4.targets file
    
before_package:
    - BuildScript.bat

build:
  project: TypeCobol.sln
  verbosity: minimal
  
artifacts: 
  - path: bin\EI_TypeCobol_Release
    name: EI_TypeCobol_Release
  - path: bin\TypeCobol_Release
    name: TypeCobol_Release

deploy:
  provider: GitHub
  auth_token: 
    secure: oX7Ck0VMD2HvWjA2Itqc+95Azad6jIkr6C0uMLoq0gK9kKfK+UIXWvwqM6oenhkG
  artifact: EI_TypeCobol_Release,TypeCobol_Release
  draft: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only

